include: package:flutter_lints/flutter.yaml

linter:

  rules:
  # Those for const keywords
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
  
  # for avoid print function
    avoid_print: true
  
  # for final keyword
    prefer_final_fields: true
    prefer_final_locals: true

  # making sure return type is declared
    always_declare_return_types: true

analyzer:
  errors:
    prefer_const_constructors: warning
    prefer_const_declarations: warning  
    prefer_const_literals_to_create_immutables: warning